// POST /api/portal?action=login — exchanges a password for a signed session.
//
// The org comes from the URL the browser is on (/portal/:slug) and is checked
// against the roster in _portal-config.js. What was typed decides the role:
//
//   PORTAL_OWNER_PASSWORD    -> owner   (read/write, any org — Josh's support login)
//   an org staff password    -> staff   (read/write, that org's whole board)
//   a partner access code    -> partner (their own referrals, and they can
//                                        write back on those)
//
// Identity comes from the credential, never from anything the browser typed.
// That matters most for partners: partnerSlug is what scopes every later
// query, so it must not be something a caller can choose.
//
// TWO KINDS OF PARTNER CREDENTIAL
// -------------------------------
// Access codes live in portal_partners as a hash, generated by the app, so the
// brokerage can add a referral firm without anyone touching Vercel. That is
// the path everything new uses.
//
// The original per-firm environment variables still work, for firms seeded
// before the change — but only while that firm has no code of its own. The
// moment one is issued, the env var stops being a way in, so migrating a
// partner closes the old door rather than leaving both open.
const { setPortalCookie } = require('../_portal-session');
const { timingSafeEqualStr } = require('../_session');
const { looksLikeAccessCode } = require('../_portal-codes');
const {
  clean,
  getOrgBySlug,
  getPartnerBySlug,
  getPartnerByCode,
  partnerHasCode,
} = require('../_portal-db');
const {
  PORTAL_ROLE_OWNER,
  PORTAL_ROLE_STAFF,
  PORTAL_ROLE_PARTNER,
  OWNER_PASSWORD_ENV,
  isKnownOrg,
  staffLogins,
  partnerLogins,
  anyPasswordConfigured,
} = require('../_portal-config');

// Small in-memory throttle to blunt guessing. Serverless instances are
// ephemeral and there can be several at once, so this is a speed bump, not a
// guarantee — the real protection is that an access code is 58 bits of
// generated entropy rather than something a person chose.
const attempts = new Map();
const WINDOW_MS = 10 * 60 * 1000;
const MAX_ATTEMPTS = 10;

function tooManyAttempts(ip) {
  const now = Date.now();
  const rec = attempts.get(ip);
  if (!rec || now - rec.first > WINDOW_MS) {
    attempts.set(ip, { first: now, count: 1 });
    return false;
  }
  rec.count += 1;
  return rec.count > MAX_ATTEMPTS;
}

function clientIp(req) {
  const fwd = req.headers['x-forwarded-for'];
  return (Array.isArray(fwd) ? fwd[0] : String(fwd || '')).split(',')[0].trim() || 'unknown';
}

// Checks what was typed against every password configured in the environment
// for this org, without short-circuiting, so response timing cannot reveal
// which login was matched (or nearly matched).
function resolveEnvLogin(password, slug) {
  const ownerPassword = process.env[OWNER_PASSWORD_ENV];
  const ownerHit = Boolean(ownerPassword) && timingSafeEqualStr(password, ownerPassword);

  let staffHit = null;
  for (const login of staffLogins(slug)) {
    const configured = process.env[login.passwordEnv];
    if (Boolean(configured) && timingSafeEqualStr(password, configured)) staffHit = login;
  }

  let partnerHit = null;
  for (const login of partnerLogins(slug)) {
    const configured = process.env[login.passwordEnv];
    if (Boolean(configured) && timingSafeEqualStr(password, configured)) partnerHit = login;
  }

  if (ownerHit) return { role: PORTAL_ROLE_OWNER, name: 'Buyer Assist', partnerSlug: null };
  if (staffHit) return { role: PORTAL_ROLE_STAFF, name: staffHit.name, partnerSlug: null };
  if (partnerHit) {
    return { role: PORTAL_ROLE_PARTNER, name: partnerHit.name, partnerSlug: partnerHit.slug, legacy: true };
  }
  return null;
}

module.exports = async function handler(req, res) {
  res.setHeader('Cache-Control', 'private, no-store');

  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ ok: false, error: 'Method not allowed.' });
  }

  const body = req.body || {};
  const slug = clean(body.org, 60).toLowerCase();
  const password = typeof body.password === 'string' ? body.password : '';

  if (!isKnownOrg(slug)) {
    return res.status(404).json({ ok: false, error: 'Unknown portal.' });
  }
  if (!password) {
    return res.status(400).json({ ok: false, error: 'Please enter your password or access code.' });
  }

  if (tooManyAttempts(clientIp(req))) {
    return res.status(429).json({ ok: false, error: 'Too many attempts. Please wait a few minutes and try again.' });
  }

  try {
    const org = await getOrgBySlug(slug);
    if (!org) {
      console.error('portal/login: no portal_orgs row for slug ' + slug);
      return res.status(500).json({ ok: false, error: 'Portal record is missing. Contact Buyer Assist.' });
    }

    let login = resolveEnvLogin(password, slug);
    let partner = null;

    // A firm that has been issued a code of its own no longer answers to its
    // old environment variable. Checked before the row is loaded, so the
    // stale password cannot mint a session even for one request.
    if (login && login.legacy && await partnerHasCode(org.id, login.partnerSlug)) {
      login = null;
    }

    // Not a configured password, so try it as an access code. Skipped for
    // anything too short to be one, which keeps mistyped passwords from
    // costing a query each. The timing difference between this branch and the
    // one above reveals only that the input was not a staff password, which
    // is not something an attacker can act on.
    if (!login && looksLikeAccessCode(password)) {
      const found = await getPartnerByCode(org.id, password);
      if (found) {
        partner = found;
        login = {
          role: PORTAL_ROLE_PARTNER,
          name: found.contact_name || found.name,
          partnerSlug: found.slug,
        };
      }
    }

    // One message for every failure — never reveal whether the credential was
    // close, or which role it nearly matched.
    if (!login) {
      // Reached only when nothing matched. A portal with no passwords set at
      // all would otherwise reject every correct one as "incorrect", which
      // reads like a bug rather than like missing config.
      if (!anyPasswordConfigured(slug)) {
        console.error('portal/login: no passwords configured for ' + slug);
        return res.status(500).json({ ok: false, error: 'This portal is not configured yet.' });
      }
      return res.status(401).json({ ok: false, error: 'Incorrect password or access code.' });
    }

    // A legacy partner password whose firm has been switched off (or renamed
    // away) is refused here rather than landing on a silently empty board.
    if (login.role === PORTAL_ROLE_PARTNER && !partner) {
      partner = await getPartnerBySlug(org.id, login.partnerSlug);
      if (!partner) {
        console.error(`portal/login: partner ${login.partnerSlug} missing or inactive for ${slug}`);
        return res.status(403).json({
          ok: false,
          error: `This access has been switched off. Contact ${org.short_name || org.name}.`,
        });
      }
    }

    setPortalCookie(res, {
      role: login.role,
      orgSlug: slug,
      partnerSlug: login.partnerSlug,
      name: login.name,
    });

    return res.status(200).json({
      ok: true,
      session: {
        role: login.role,
        name: login.name,
        orgSlug: slug,
        orgName: org.name,
        partner: partner
          ? { slug: partner.slug, name: partner.name, kind: partner.kind, accent: partner.accent }
          : null,
      },
    });
  } catch (err) {
    console.error('portal/login: ' + err.message);
    return res.status(500).json({ ok: false, error: 'Could not sign you in right now.' });
  }
};
