// Access codes for referral partners.
//
// A partner's credential is generated by the server, shown to the brokerage
// exactly once, and stored only as a hash. There is no "remind me" and no
// reset link: if a firm loses their code, Ben issues a new one, which is a
// single click and invalidates the old one at the same time.
//
// WHY A GENERATED CODE RATHER THAN A CHOSEN PASSWORD
// --------------------------------------------------
// The person choosing it is not the person using it. Ben would be picking a
// password on behalf of a conveyancer, which reliably produces the firm name
// with a year on the end. Generating it removes that failure entirely, and
// the thing being protected is other people's names, mobiles and loan
// positions.
//
// FORMAT
// ------
// Three groups of four from a 30-character alphabet: 30^12, about 58 bits.
// The alphabet drops 0/O, 1/I/L and U — the characters that get misread when
// a code is read out over the phone, and the one that turns codes into words.
// Dashes and case are cosmetic: normalise() strips them before hashing, so
// "wq4k-7hmp-3ntz" and "WQ4K7HMP3NTZ" are the same code.
const crypto = require('crypto');

const ALPHABET = '23456789ABCDEFGHJKMNPQRSTVWXYZ';
const GROUPS = 3;
const GROUP_LEN = 4;
const CODE_LEN = GROUPS * GROUP_LEN;

// Shortest thing worth sending to the database as a candidate code. Anything
// below this is a mistyped password, and skipping it keeps junk sign-in
// attempts from costing a query each.
const MIN_CANDIDATE_LEN = 8;

function generateAccessCode() {
  const groups = [];
  for (let g = 0; g < GROUPS; g += 1) {
    let group = '';
    // randomInt is uniform over the range and draws from the CSPRNG. Doing
    // this with randomBytes and a modulo would bias the low characters.
    for (let i = 0; i < GROUP_LEN; i += 1) group += ALPHABET[crypto.randomInt(ALPHABET.length)];
    groups.push(group);
  }
  return groups.join('-');
}

// What the user typed, reduced to what was actually meant. Case and dashes
// carry no information, so a code copied out of an email with a trailing
// space still works.
function normaliseAccessCode(input) {
  return String(input == null ? '' : input).toUpperCase().replace(/[^0-9A-Z]/g, '');
}

// True for anything long enough to be worth a lookup. Deliberately loose: a
// code from a future format change must still reach the database rather than
// being rejected by a length check here.
function looksLikeAccessCode(input) {
  return normaliseAccessCode(input).length >= MIN_CANDIDATE_LEN;
}

// Bound to the org, so the same plaintext under two brokerages produces two
// different hashes. Returns null for anything too short to be a code, which
// is the caller's signal to skip the query.
function hashAccessCode(orgId, code) {
  const norm = normaliseAccessCode(code);
  if (!orgId || norm.length < MIN_CANDIDATE_LEN) return null;
  return crypto.createHash('sha256').update(`portal:${orgId}:${norm}`).digest('hex');
}

// Groups a normalised code for display. Only used on the one screen that
// ever sees a code in the clear.
function formatAccessCode(code) {
  const norm = normaliseAccessCode(code);
  if (!norm) return '';
  return (norm.match(/.{1,4}/g) || []).join('-');
}

module.exports = {
  ALPHABET,
  CODE_LEN,
  generateAccessCode,
  normaliseAccessCode,
  looksLikeAccessCode,
  hashAccessCode,
  formatAccessCode,
};
